{% set name = "Flask-Security" %}
{% set version = "3.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "d61daa5f5a48f89f30f50555872bdf581b2c65804668b0313345cd7beff26432" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - flask >=0.11
    - flask-login >=0.3.0
    - flask-mail >=0.7.3
    - flask-principal >=0.3.3
    - flask-wtf >=0.13.1
    - itsdangerous >=0.21
    - passlib >=1.7

test:
  imports:
    - flask_security
    - flask_security.changeable
    - flask_security.confirmable
    - flask_security.core
    - flask_security.datastore
    - flask_security.decorators
    - flask_security.forms
    - flask_security.passwordless
    - flask_security.recoverable
    - flask_security.registerable
    - flask_security.script
    - flask_security.signals
    - flask_security.utils
    - flask_security.views

about:
  home: https://github.com/mattupstate/flask-security
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Simple security for Flask apps'
  dev_url: https://github.com/mattupstate/flask-security
  doc_url: https://pythonhosted.org/Flask-Security/

extra:
  recipe-maintainers:
    - pmlandwehr
