{% set python_min = "3.9" %}
{% set name = "Flask-Security" %}
{% set version = "5.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 0139eef4b5a3f44387a96c85cc880b84449156f70882451f781a4dea7ad3ec8a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - flit-core >=3.8,<4
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}
    - flask >=3.0.0
    - flask-login >=0.6.3
    - flask-principal >=0.4.0
    - flask-wtf >=1.1.2
    - email-validator >=2.0.0
    - markupsafe >=2.1.0
    - passlib >=1.7.4
    - wtforms >=3.0.0
    - importlib_resources >=5.10.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - flask_security

about:
  home: https://github.com/pallets-eco/flask-security
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  summary: 'Quickly add security features to your Flask application'
  dev_url: https://github.com/pallets-eco/flask-security
  doc_url: https://flask-security.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - nicoddemus
    - williamjamir
