{% set name = "Flask-Security" %}
{% set version = "5.5.2" %}
{% set bundle = "tar.gz" %}
{% set hash = "0139eef4b5a3f44387a96c85cc880b84449156f70882451f781a4dea7ad3ec8a" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  host:
    - python
    - setuptools
    - babel >=1.3
    - pytest-runner >=2.6.2

  run:
    - python
    - flask >=0.11
    - flask-login >=0.3.0
    - flask-mail >=0.7.3
    - flask-principal >=0.3.3
    - flask-wtf >=0.13.1
    - flask-babelex >=0.9.3
    - itsdangerous >=0.21
    - passlib >=1.7
    - flask-script

test:
  imports:
    - flask_security
    - flask_security.changeable
    - flask_security.confirmable
    - flask_security.core
    - flask_security.datastore
    - flask_security.decorators
    - flask_security.forms
    - flask_security.passwordless
    - flask_security.recoverable
    - flask_security.registerable
    - flask_security.script
    - flask_security.signals
    - flask_security.utils
    - flask_security.views

about:
  home: https://github.com/mattupstate/flask-security
  license: MIT
  license_file: LICENSE.txt
  # license_file: No reference to LICENSE in MANIFEST.in - see https://github.com/mattupstate/flask-security/pull/544
  license_family: MIT
  summary: 'Simple security for Flask apps'
  dev_url: https://github.com/mattupstate/flask-security
  doc_url: https://pythonhosted.org/Flask-Security/

extra:
  recipe-maintainers:
    - pmlandwehr
    - nicoddemus
    - williamjamir
