travis:
  secure:
    BINSTAR_TOKEN: ZI3vBjHfdAizNnqpuu97xTHf+U+rxSKdxn3iVxI0RuX3x7PWPR6LlaLHTFGEaPs1Cnz9G3NvaW00NrGFLAlb/Vbi+Jnws90PrB9UyTb4AYk9UNYKcBh+S6h4O7YcMtRbFwScLYIrDzotQaD9HcAUkL3WQmsWLMX9pjF8pIQf7oMLKDbkpJP7khh2jHB2w7pCPstmJZSjX5NOdsEdsehu5KHiS6XITSLWcWiOpwHvD2VNbBle8XmKlrud3X0XctpXxqmD8AyUinV+qCdJG+8oS5FxXK5pdPj0jKm0LMmjOh1YwBpwmmmDW5tJcdWZhpdz9yzlMaZmKehe/Ymk9KdL3wm2pFK/rj+1GP+0TenAIw/L9zobgHV1mg/69mY5Y/+m09LohytziovypYRfsGzzHdgCWEc1iNh3fkwLQWseh+M/bFDFeaXSWAqnxfcI3McinJmRHLDp5JDAACreuTyFjkajyUqLqUpM6uVEPRVfzOmUKAGMRyEoOJUKBnJeZ7p3sqGCV/DOTePyjOPw1s5fYUMamrUzeyiuqiDSYet0ZmAUjKuMOMeangHVbSA6Pay/U+cMYG7vtgtkhFDGWX2HNu+DjnAyDh7+URDjv77I3ZIrKExXVrLuKkvtfc+/HU9YNrVHZuKbxworShF/85X7NdNp3LcPeyFBzOBJCQEBj1A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
