travis:
  secure:
    BINSTAR_TOKEN: Ix4VQRep4Dd0dtmXqhmK3O/XahLGQZiLBAkG10uqTH10fJOdKq7HHNNYjyywTs0HHcmHhVvkC1I5fDpEk8yJNNfGQFs8BXXfLDJquuIaCtoPVj0UTOKFWuzjBMpYcn5eF0+cN4GrIOwYf173VzkVBnxvEQtCULt6hdFa95x6K8p6MSb216jvs4v65Vjtt896PSEUOm0QRWmrAuLG+GgTFNKSh9243pDMKmPpqRxIgsRAep5SMHLHIIxa+2HbexiXt4lgZ1kluCosmGg8gIofecmhnP20w9mcm9LQSK0oi7pptp6OK1j4rWdAoUeyI1u+0tkQ9ot1AwpI10rWpbfWpUiHWlRf7s6t8xgRVsgAVQ7Gxg/TMOfF+KDlyjLyJ9xGVdy3vLMInb+NOlDowiTYl/H8FU/ZCFh8/WQzxiP7lqC3fBEuDS7Np8+BxNSPSQR8WS0PmG5uDiMp0aHbE4muHazAC0QSuOeTtSJLwETjTIskQEhIvPz7vUM+3wcbukzSya18bbChUVxCLIui8nW63L8Fc+XLXsdl6sxf9oDOkB7zGoyAHewYplrRAlpFIqw6062dE4HKbeEI31s4wIRccKEDBnAaOyOuZXZO6E2pmifM/mumUSvEsRMtIv2rKq4V0v26tInyknuEiK0hlk4NtzVQFcTZ4XJOpupueQ0FJBw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
